export default [
  "oficeja administracio",
  "arkitekturo/geodezio",
  "edukado/instruado",
  "farmacio/biotekniko",
  "gastronomio",
  "turismo/gastejoj",
  "homaj resursoj",
  "komputiko",
  "inĝenierio",
  "normkontrolo",
  "financoj/ekonomio",
  "merkatiko/reklamado/publikaj rilatoj",
  "medicino/kuraco",
  "industrio/produktado",
  "vendado/priservado",
  "tradukado",
  "studoj de evoluo",
  "konsultado",
  "energetiko/elektroniko",
  "desegnarto/fotografio",
  "interreto/retkomerco",
  "transporto/distribuo/ekspedo",
  "kosmetiko/flegado",
  "kulturo/artoj/amuzado",
  "manlaboro",
  "agronomio/agrikulturo",
  "protektado",
  "juro/juĝado",
  "mediprotektado",
  "telekomunikado",
  "asekuro",
  "franĉizo",
];
