export default [
  "Afganio",
  "Alando",
  "Albanio",
  "Alĝerio",
  "Andoro",
  "Angolo",
  "Angvilo",
  "Antarkto",
  "Antigvo-Barbudo",
  "Argentino",
  "Armenio",
  "Arubo",
  "Aŭstralio",
  "Aŭstrio",
  "Azerbajĝano",
  "Bahamoj",
  "Bangladeŝo",
  "Barato",
  "Barbado",
  "Barejno",
  "Belgio",
  "Belizo",
  "Belorusio",
  "Benino",
  "Bermudoj",
  "Birmo",
  "Bocvano",
  "Bolivio",
  "Bonero",
  "Bosnio kaj Hercegovino",
  "Brazilo",
  "Brita Hindoceana Teritorio",
  "Britaj Virgulininsuloj",
  "Britio",
  "Brunejo",
  "Bulgario",
  "Burkino",
  "Burundo",
  "Butano",
  "Buvetinsulo",
  "Ĉado",
  "Ĉeĥio",
  "Centr-Afrika Respubliko",
  "Ĉilio",
  "Ĉinio",
  "Danio",
  "Demokratia Respubliko Kongo",
  "Domingo",
  "Dominiko",
  "Ebur-Bordo",
  "Egiptio",
  "Ekvadoro",
  "Ekvatora Gvineo",
  "Eritreo",
  "Estonio",
  "Etiopio",
  "Falklandoj",
  "Farneoj",
  "Ferooj",
  "Fiĝioj",
  "Filipinoj",
  "Finnlando",
  "Franca Gviano",
  "Franca Polinezio",
  "Francaj Sudaj Teritorioj",
  "Francio",
  "Gabono",
  "Gambio",
  "Ganao",
  "Germanio",
  "Gernezejo",
  "Ĝibraltaro",
  "Ĝibutio",
  "Grekio",
  "Grenado",
  "Gronlando",
  "Gujano",
  "Gvadelupo",
  "Gvamo",
  "Gvatemalo",
  "Gvineo",
  "Gvineo Bisaŭa",
  "Haitio",
  "Herda kaj Makdonaldaj Insuloj",
  "Hispanio",
  "Honduro",
  "Honkongo",
  "Hungario",
  "Indonezio",
  "Irako",
  "Irano",
  "Irlando",
  "Islando",
  "Israelo",
  "Italio",
  "Jamajko",
  "Japanio",
  "Jemeno",
  "Jordanio",
  "Ĵerzejo",
  "Kabo-Verdo",
  "Kamboĝo",
  "Kameruno",
  "Kanado",
  "Kartvelio",
  "Kataro",
  "Kazaĥio",
  "Kejmanoj",
  "Kenjo",
  "Kipro",
  "Kirgizio",
  "Kiribato",
  "Kokosinsuloj",
  "Kolombio",
  "Komoroj",
  "Kosovo",
  "Kostariko",
  "Kristnaskinsulo",
  "Kroatio",
  "Kubo",
  "Kukinsuloj",
  "Kuracao",
  "Kuvajto",
  "Laoso",
  "Latvio",
  "Lesoto",
  "Libano",
  "Liberio",
  "Libio",
  "Liĥtenŝtejno",
  "Litovio",
  "Luksemburgo",
  "Madagaskaro",
  "Majoto",
  "Makao",
  "Malajzio",
  "Malavio",
  "Maldivoj",
  "Malio",
  "Malto",
  "Manksinsulo",
  "Maroko",
  "Marŝaloj",
  "Martiniko",
  "Maŭricio",
  "Maŭritanio",
  "Meksiko",
  "Mikronezio",
  "Moldavio",
  "Monako",
  "Moncerato",
  "Mongolio",
  "Montenegro",
  "Mozambiko",
  "Namibio",
  "Nauro",
  "Nederlandaj Antiloj",
  "Nederlando",
  "Nepalo",
  "Niĝerio",
  "Niĝero",
  "Nikaragvo",
  "Niuo",
  "Nord-Koreio",
  "Nord-Makedonio",
  "Nord-Marianoj",
  "Norfolkinsulo",
  "Norvegio",
  "Nov-Kaledonio",
  "Nov-Zelando",
  "Okcidenta Saharo",
  "Omano",
  "Orienta Timoro",
  "Pakistano",
  "Palaŭo",
  "Palestinaj Teritorioj",
  "Panamo",
  "Papuo-Nov-Gvineo",
  "Paragvajo",
  "Peruo",
  "Pitkarna Insulo",
  "Pollando",
  "Portugalio",
  "Puerto-Riko",
  "Respubliko Kongo",
  "Reunio",
  "Ruando",
  "Rumanio",
  "Rusio",
  "Salomonoj",
  "Salvadoro",
  "Samoo",
  "San-Marino",
  "Sankta Bartolomeo",
  "Sankta Heleno",
  "Sankta Kristofo kaj Neviso",
  "Sankta Lucio",
  "Sankta Marteno",
  "Sankta Piero kaj Mikelono",
  "Sankta Vincento kaj la Grenadinoj",
  "Sao-Tomeo kaj Principeo",
  "Saŭda Arabio",
  "Sejŝeloj",
  "Senegalo",
  "Serbio",
  "Siera-Leono",
  "Singapuro",
  "Sirio",
  "Slovakio",
  "Slovenio",
  "Somalio",
  "Sri-Lanko",
  "Sud-Afriko",
  "Sud-Georgio kaj Sud-Sandviĉinsuloj",
  "Sud-Koreio",
  "Sudano",
  "Sud-Sudano",
  "Surinamo",
  "Svalbardo kaj Jan-Majen-insulo",
  "Svazilando",
  "Svedio",
  "Svislando",
  "Taĝikio",
  "Tajlando",
  "Tajvano",
  "Tanzanio",
  "Togo",
  "Tokelao",
  "Tongo",
  "Trinidado kaj Tobago",
  "Tunizio",
  "Turkio",
  "Turkmenio",
  "Turkoj kaj Kajkoj",
  "Tuvalo",
  "Ugando",
  "Ukrainio",
  "Unuiĝintaj Arabaj Emirlandoj",
  "Urugvajo",
  "Usona Samoo",
  "Usonaj Malgrandaj Insuloj",
  "Usonaj Virgulininsuloj",
  "Usono",
  "Uzbekio",
  "Valiso kaj Futuno",
  "Vanuatuo",
  "Vatikano",
  "Venezuelo",
  "Vjetnamio",
  "Zambio",
  "Zimbabvo",
];
